# Maintenance mode flag
maintenance_mode: false

support_mail_account: "support@orbitals.fuchs-kiel.de"

# List of email addresses to send error logs to
error_log_emails:
  - "niklas@fuchs-kiel.de"

smtp_server: "saiph.fuchs-kiel.de"
smtp_port: 587

messages_mail_account: "noreply@orbitals.fuchs-kiel.de"
messages_mail_account_pass: "10,%,ImEtTOrkom"

link_base_url: "http://127.0.0.1:5000"

signup_enabled: true

#In seconds
mail_verify_token_time: 3600
password_reset_token_time: 3600

reset_secret_key: "NK2EjDq7sLk5dmqrmri4xMIUwoQGY11jr4wEdp7zYlXehS4Vtprgf0lcI4s1cecGxKsxbZW26lcrR1iU5DT1aaEY2sqjQgE05TJcjzljIWRjx2sQvAHTLuYAmoR8waIX"
verify_secret_key: "C4WMLM4FukFE8DvPKCIh5mPKrrdeKyDqSexJUI4qv357EnrJCwKdT3ukAhVBelLuMnUEZI27TJmKhFuIyk348ghWzRAEHDwjXt2GDt6FAP3a7v0e0WvWGCAtGI9QavPW"

flask_secret_key: "s9FAbd9GR9hgs4dFE2pWkB8Qt2iHJTNuavJB1cCdRp13yrJPZLHy3GJk2bP8mTLPg07IET19aan84vN5hscz3XSoSznJSu0iji4PvSzWtNq2UfFwPraGYJSh7xydJdBP"